### ISSUE TITLE
Semantics of rectangle-based conditions differ

### ISSUE THREAD

**Issue by dpaetzel** [rpreen/xcsf#116]
Center-spread conditions define fully open intervals $(c - s, c + s)$ since there's a `distance < 1` comparison in `match` and `distance < 1` if `distance < s` and `distance == 1` if `distance == s`.

On the other hand, [unordered-bound conditions](https://github.com/xcsf-dev/xcsf/blob/cd2f9d93929b6ce0eee13cfbaca2d8d3a84fbff3/xcsf/cond_rectangle.c#L190) define closed intervals $[l, u]$ since if `x[i] < l || x[i] > u` the condition does not match.

This should probably be documented or fixed?

I personally will probably not use ubr right now; but I noticed this and wanted to create an issue anyway, just in case.

**Comment by dpaetzel** [comment]
A probably separate issue/discussion may be whether fully open intervals are the way to go? Fully open means that the input space can never be fully covered without overlaps (despite such a solution being found by XCSF ever being very improbable); it may be semantically cleaner to have half-open intervals here? (I.e. $[c - s, c + s)$.)

**Comment by rpreen** [comment]
The CSR is implemented with the distance calculation to make it directly comparable with the hyperellipsoids and is based on Stalph & Butz's Java implementation. But I'm happy to change it to be more similar to UBR - although I doubt it will make any real difference in performance.
