### ISSUE TITLE
Module not found error on Windows & Mac

### ISSUE THREAD

**Issue by tschaffroth** [rpreen/xcsf#13]
Hi @rpreen, 

after downloading and building the files according to your instructions i'm receiving the following error both on Mac OS and Windows 10 64 Bit when running any of the python scripts in the build-directory:

File "...\xcsf\build\example_maze.py", line 31, in <module>  import xcsf.xcsf as xcsf, Module Not Found

On Windows my Python version is 3.9.0, CMake version is 3.19.2.

Can you help here? In case you need additional information just hit me up.

Best

**Comment by rpreen** [comment]
Hi,

Can you confirm that you are running `python example_maze.py` from within the build folder (sample place as running cmake) and that in the build folder there is a newly created folder `xcsf` with the module files built by cmake? On Windows, the python module files that should have been built include the file `xcsf.pyd` and `libxcs.a`.

**Comment by rpreen** [comment]
Closing this issue since it's been such a long time...

**Comment by rpreen** [comment]
This is possibly related to changes from Python 3.8+ where the search paths of DLL dependencies has been reset: https://cython.readthedocs.io/en/latest/src/tutorial/appendix.html

With Python 3.10 in a Windows 10 VM, I'm currently getting the following error:

ImportError: DLL load failed while importing xcsf: The specified module could not be found.
