### ISSUE TITLE
Make option setting and getting symmetrical (Python bindings)

### ISSUE THREAD

**Issue by dpaetzel** [rpreen/xcsf#15]
Currently, some options are set using strings but when their value is read, an integer is returned:

```Python
from xcsf.xcsf import XCS

xcs = XCS(1,1,1)
print(xcs.EA_SELECT_TYPE) # prints 0
xcs.EA_SELECT_TYPE = "roulette"
print(xcs.EA_SELECT_TYPE) # prints 0
xcs.EA_SELECT_TYPE = "tournament"
print(xcs.EA_SELECT_TYPE) # prints 1
```

I think the library would benefit from having symmetrical option setting and getting. For example, I'm currently preparing experiments as follows.

A have a module that interacts with the XCSF library for me, this module contains e.g.

```Python
def default_xcs_params():
    xcs = xcsf.XCS(1, 1, 1)
    return get_xcs_params(xcs)

def get_xcs_params(xcs):
    return {
        "OMP_NUM_THREADS": xcs.OMP_NUM_THREADS,
        "POP_INIT": xcs.POP_INIT,
        ...
        "EA_SELECT_TYPE": xcs.EA_SELECT_TYPE,
        ...
    }

def set_xcs_params(xcs, params):
    xcs.OMP_NUM_THREADS = params["OMP_NUM_THREADS"]
    xcs.POP_INIT = params["POP_INIT"]
    ...
    xcs.EA_SELECT_TYPE = params["EA_SELECT_TYPE"]
    ...
```

In my experiment code I want to override only the relevant settings (without
accessing the `XCS()` object directly):

```Python
params = default_xcs_params() | {
    "MAX_TRIALS" : 100000,
    "POP_SIZE": 100,
}
```

However, that does not work currently because `get_xcs_params` returning `int`s for options that `set_xcs_params` expects to be `str`s.

I haven't found the time to look into how hard it would be to have the Python bindings return strings.

**Comment by dpaetzel** [comment]
I just noticed that this actually works for `LOSS_FUNC`.

**Comment by dpaetzel** [comment]
Turns out that fixing this was surprisingly straightforward because everything that was needed was already there.

**Comment by rpreen** [comment]
Thanks for fixing this; making it symmetrical definitely makes sense.
