### ISSUE TITLE
Initialization of center-spread rectangular conditions may be suboptimal

### ISSUE THREAD

**Issue by dpaetzel** [rpreen/xcsf#62]
I noticed that center-spread conditions seem to be generally larger (and often protrude a lot out of the input space defined by the `min` and `max` condition attributes) than unordered-bound conditions.

In [this line](https://github.com/rpreen/xcsf/blob/4cce6ef1088e7b0e47881e5603346002478288a3/xcsf/cond_rectangle.c#L71), the maximum spread of center-spread rectangular conditions is set to

```
const double spread_max = fabs(xcsf->cond->max - xcsf->cond->min);
```

However, shouldn't this value be divided by two? The way that spread is used in `cond_rectangle_dist`, it defines lower and upper bounds by

```
lower = center - spread
upper = center + spread
```

**Comment by rpreen** [comment]
It's difficult to say without running some experiments to compare. Only the center really needs to be clamped within the bounds of the input space for CSR since evolution will take care of shrinking the spread to increase fitness.

**Comment by rpreen** [comment]
I probably tended towards having them a little more general than specific during initialisation because I once was trying to get them to work for a 256 dimensional problem and it just kept covering repeatedly...

**Comment by dpaetzel** [comment]
I guess you're right. Ultimately this is a question of hyperparametrization and not a bug.
