### ISSUE TITLE
Support early stopping or maybe even callbacks

### ISSUE THREAD

**Issue by dpaetzel** [rpreen/xcsf#70]
Hi! I think early stopping could be a nice feature. I currently don't have the time to implement it but thought, I'd suggest it anyways :wink:

For example, `XCS.fit(X, y)` could check whether error changes “enough” (error is measured anyways for the CLI output); the user should probably be able to configure a delta (and maybe also a window how often that delta is checked for).

This would be especially helpful since right now there's no way to stop a `XCS.fit(X, y)` call and those calls can take long (i.e. minutes) without any progress being made.

As an alternative: Support callbacks of some sort (i.e. Python code run after each iteration) from which a stop signal can be given to XCS. I presume that this is more difficult (or impossible?) to implement, though, due to the interactions with the C library. An example for this is the [Optuna's callback support](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/007_optuna_callback.html) where the callback receives a `Study` object whose `stop()` method can be called.

**Comment by rpreen** [comment]
Although not as nice as callbacks, this can be done currently from Python using the `store()` and `retrieve()` functions as shown in the regression [example](https://github.com/rpreen/xcsf/blob/master/python/example_regression.py).

In a loop that repeatedly calls `fit()` you just have to checkpoint the system by calling `store()` whenever desired:

https://github.com/rpreen/xcsf/blob/d051ebfc0e67500d1cd9cbdc34a1da0ea6ef9d45/python/example_regression.py#L157-L170

And then at the end, rollback the system to the checkpoint with `retrieve()`:

https://github.com/rpreen/xcsf/blob/d051ebfc0e67500d1cd9cbdc34a1da0ea6ef9d45/python/example_regression.py#L200-L206

**Comment by dpaetzel** [comment]
Oh, you're right. I'm sorry, I entirely forgot that `XCS.fit(X, y)` does not start from scratch each time (as is done e.g. by sklearn estimators).
